// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqJVJKqJVJKqJVJKqJVJKqJVJKqJVJKqJ',
    appId: '1:472385734556:web:77791fc6850b29d0c7aa59',
    messagingSenderId: '472385734556',
    projectId: 'hiotaku-flutter',
    authDomain: 'hiotaku-flutter.firebaseapp.com',
    storageBucket: 'hiotaku-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqJVJKqJVJKqJVJKqJVJKqJVJKqJVJKqJ',
    appId: '1:472385734556:android:77791fc6850b29d0c7aa59',
    messagingSenderId: '472385734556',
    projectId: 'hiotaku-flutter',
    storageBucket: 'hiotaku-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqJVJKqJVJKqJVJKqJVJKqJVJKqJVJKqJ',
    appId: '1:472385734556:ios:77791fc6850b29d0c7aa59',
    messagingSenderId: '472385734556',
    projectId: 'hiotaku-flutter',
    iosBundleId: 'com.hiotaku.app',
    storageBucket: 'hiotaku-flutter.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqJVJKqJVJKqJVJKqJVJKqJVJKqJVJKqJ',
    appId: '1:472385734556:macos:77791fc6850b29d0c7aa59',
    messagingSenderId: '472385734556',
    projectId: 'hiotaku-flutter',
    storageBucket: 'hiotaku-flutter.firebasestorage.app',
    iosBundleId: 'com.hiotaku.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqJVJKqJVJKqJVJKqJVJKqJVJKqJVJKqJ',
    appId: '1:472385734556:windows:77791fc6850b29d0c7aa59',
    messagingSenderId: '472385734556',
    projectId: 'hiotaku-flutter',
    authDomain: 'hiotaku-flutter.firebaseapp.com',
    storageBucket: 'hiotaku-flutter.firebasestorage.app',
  );
}
